main:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts


  # Example: parent item with dropdown submenu children
  # - name: More
  #   weight: 30
  #   params:
  #     icon: layers

  - name: Categories
    weight: 20
    pageRef: /categories
    # parent: More
    params:
      icon: categories

  - name: Tags
    weight: 40
    pageRef: /tags
    # parent: More
    params:
      icon: tags

  - name: Series
    weight: 30
    pageRef: /series
    # parent: More
    params:
      icon: bookmark

  - name: About
    pageRef: /about
    weight: 50
    params:
      icon: about
  # - name: Projects
  #   weight: 60
  #   pageRef: /projects
  #   # parent: More
  #   params:
  #     icon: projects



# footer menu
footer:
  # - name: Timeline
  #   pageRef: /timeline
  #   weight: 10
  #   params:
  #     icon: chart

  - name: Archives
    pageRef: /archives
    weight: 10
    params:
      icon: archive

  - name: RSS Feed
    url: /index.xml
    weight: 20
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/Cool-Byte01
    params:
      icon: github
  - name: Instagram
    url: https://instagram.com/_hfish
    params:
      icon: instagram
  - name: Email
    url: mailto:hfisk1001@gmai.com
    params:
      icon: email

